project_id = "dwghdxhzsvyzasqnnukv"

[functions.manage-confirmer]
verify_jwt = false

[functions.generate-landing]
verify_jwt = false

[functions.generate-landing-image]
verify_jwt = false

[functions.gemini-image]
verify_jwt = false
